---
# tasks file for kibana

- name: Download Kibana RPM
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-6.4.0-x86_64.rpm
    dest: /tmp/
    
- name: Install Kibana RPM
  yum: 
    name: /tmp/kibana-6.4.0-x86_64.rpm
    state: present

- name: Copy Conf File
  copy:
    src: /reancloud/elk/playbooks/roles/kibana/files/kibana.yml
    dest: /etc/kibana/
    force: yes

- name: Enable Kibana Service -- chkconfig
  service:
    name: kibana
    enabled: yes

- name: Start Kibana service
  service:
    name: kibana
    state: started
  

