---
# tasks file for logstash

- name: Download Logstash RPM
  get_url:
    url: https://artifacts.elastic.co/downloads/logstash/logstash-6.4.0.rpm
    dest: /tmp/

- name: Install Logstash RPM
  yum:
    name: /tmp/logstash-6.4.0.rpm
    state: present

- name: Copy Conf File
  copy:
    src: /reancloud/elk/playbooks/roles/logstash/files/logstash.conf
    dest: /etc/logstash/logstash.conf

- name: Start Logstash
  shell: /usr/share/logstash/bin/logstash -f /etc/logstash/logstash.conf & 
    
