---
# tasks file for logstash

- name: Download Logstash Signing Key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add logstash config repo to yum repos
  copy:
    src: /reancloud/elk/playbooks/roles/logstash/files/logstash.repo  
    dest: /etc/yum.repos.d/

- name: Install Logstash RPM
  yum:
    name: logstash
    state: latest

- name: Copy Conf File
  copy:
    src: /reancloud/elk/playbooks/roles/logstash/files/logstash.conf
    dest: /etc/logstash/logstash.conf

- name: Start Logstash
  service:
     name: logstash
     state: started

- name: Run Logstash command
  shell: /usr/share/logstash/bin/logstash -f /etc/logstash/logstash.conf

    
